export const APP_INIT = "APP_INIT";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SET_SELECTED_EMPLOYEE_ID = "SET_SELECTED_EMPLOYEE_ID";
export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SAVE_EMPLOYEE = "SAVE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const SET_SELECTED_DEPARTMENT_ID = "SET_SELECTED_DEPARTMENT_ID";
export const SAVE_DEPARTMENT = "SAVE_DEPARTMENT";
export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
